// <auto-generated />
namespace Notify.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fecha_de_nuevo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fecha_de_nuevo));
        
        string IMigrationMetadata.Id
        {
            get { return "201802261540148_fecha_de_nuevo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
